from __future__ import annotations

import asyncio
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Literal

import numpy as np
import onnxruntime as ort
from numpy.typing import NDArray
from tokenizers import Tokenizer

from lode.domain.exceptions import EmbeddingError
from lode.domain.interfaces import EmbeddingProvider
from lode.domain.models import Embeddings


class OnnxTextEmbeddingAdapter(EmbeddingProvider):
    """
    Sentence embedding provider backed by an ONNX Runtime model.

    The adapter is model-agnostic and supports HuggingFace sentence
    embedding models exported to ONNX, provided the expected directory
    layout is present.

    Embeddings are generated by:

    1. Tokenizing input texts.
    2. Running the ONNX encoder.
    3. Applying attention-mask mean pooling.
    4. Applying L2 normalization.

    E5-compatible models automatically receive the appropriate
    query/document prefixes before inference.
    """

    _E5_PREFIXES = {
        "query": "query: ",
        "document": "passage: ",
    }

    def __init__(
        self,
        model_dir: Path,
        *,
        max_sequence_length: int = 512,
        intra_op_threads: int = 1,
        inter_op_threads: int = 1,
    ) -> None:
        self._model_dir = model_dir.resolve()

        self._validate_model_directory()

        self._max_sequence_length = max_sequence_length

        self._tokenizer = self._create_tokenizer()

        self._session = self._create_session(
            intra_op_threads=intra_op_threads,
            inter_op_threads=inter_op_threads,
        )

        self._output_name = (
            self._session.get_outputs()[0].name
        )


    @property
    def _onnx_dir(self) -> Path:
        return self._model_dir / "onnx"


    @property
    def _model_path(self) -> Path:
        return self._onnx_dir / "model.onnx"


    @property
    def _tokenizer_path(self) -> Path:
        return self._onnx_dir / "tokenizer.json"


    @property
    def _config_path(self) -> Path:
        return self._onnx_dir / "config.json"


    @property
    def _tokenizer_config_path(self) -> Path:
        return self._onnx_dir / "tokenizer_config.json"


    def _validate_model_directory(self) -> None:
        """Validate the expected ONNX model layout."""

        if not self._model_dir.exists():
            raise EmbeddingError(
                f"Model directory does not exist: {self._model_dir}"
            )

        if not self._model_dir.is_dir():
            raise EmbeddingError(
                f"Model path is not a directory: {self._model_dir}"
            )


        required_files = (
            self._model_path,
            self._tokenizer_path,
            self._config_path,
            self._tokenizer_config_path,
        )

        for file in required_files:
            if not file.exists():
                raise EmbeddingError(
                    f"Required model file not found: {file}"
                )

        for json_file in (
            self._config_path,
            self._tokenizer_config_path,
        ):
            try:
                with json_file.open(
                    "r",
                    encoding="utf-8",
                ) as f:
                    json.load(f)
            except Exception as exc:
                raise EmbeddingError(
                    f"Invalid JSON file: {json_file}"
                ) from exc


    @staticmethod
    def _build_session_options(
        *,
        intra_op_threads: int,
        inter_op_threads: int,
    ) -> ort.SessionOptions:
        """Create optimized ONNX Runtime session options."""

        options = ort.SessionOptions()

        options.graph_optimization_level = (
            ort.GraphOptimizationLevel.ORT_ENABLE_ALL
        )

        options.enable_mem_pattern = True
        options.enable_cpu_mem_arena = True

        options.intra_op_num_threads = intra_op_threads
        options.inter_op_num_threads = inter_op_threads

        return options


    def _create_session(
        self,
        *,
        intra_op_threads: int,
        inter_op_threads: int,
    ) -> ort.InferenceSession:
        return ort.InferenceSession(
            str(self._model_path),
            sess_options=self._build_session_options(
                intra_op_threads=intra_op_threads,
                inter_op_threads=inter_op_threads,
            ),
            providers=["CPUExecutionProvider"],
        )


    def _create_tokenizer(self) -> Tokenizer:
        return Tokenizer.from_file(
            str(self._tokenizer_path)
        )


    def _tokenize(
        self,
        texts: tuple[str, ...],
    ) -> Mapping[str, NDArray[np.int64]]:
        """
        Tokenize a batch of texts into ONNX inputs.
        """

        encodings = self._tokenizer.encode_batch(
            list(texts),
        )

        truncated_ids = [
            encoding.ids[: self._max_sequence_length]
            for encoding in encodings
        ]

        batch_max_length = max(
            len(ids)
            for ids in truncated_ids
        )

        input_ids = []
        attention_mask = []
        token_type_ids = []

        has_token_type_ids = any(
            encoding.type_ids
            for encoding in encodings
        )

        for encoding, ids in zip(
            encodings,
            truncated_ids,
        ):
            padding = batch_max_length - len(ids)

            input_ids.append(
                ids + [0] * padding
            )

            attention_mask.append(
                [1] * len(ids)
                + [0] * padding
            )

            if has_token_type_ids:
                token_type_ids.append(
                    encoding.type_ids[: self._max_sequence_length]
                    + [0] * padding
                )

        inputs: dict[str, NDArray[np.int64]] = {
            "input_ids": np.asarray(
                input_ids,
                dtype=np.int64,
            ),
            "attention_mask": np.asarray(
                attention_mask,
                dtype=np.int64,
            ),
        }

        if has_token_type_ids:
            inputs["token_type_ids"] = np.asarray(
                token_type_ids,
                dtype=np.int64,
            )

        return inputs


    def _run_inference(
        self,
        inputs: Mapping[str, NDArray[np.int64]],
    ) -> NDArray[np.float32]:
        """
        Execute the ONNX model and return the last hidden states.
        """

        try:
            outputs = self._session.run(
                [self._output_name],
                inputs,
            )

        except Exception as exc:
            raise EmbeddingError(
                "ONNX inference failed."
            ) from exc

        return outputs[0].astype(np.float32, copy=False)

    @staticmethod
    def _mean_pool(
        hidden_states: NDArray[np.float32],
        attention_mask: NDArray[np.int64],
    ) -> NDArray[np.float32]:
        """
        Mean pool token embeddings using the attention mask.
        """

        mask = attention_mask.astype(np.float32)[..., None]

        summed = np.sum(
            hidden_states * mask,
            axis=1,
        )

        counts = np.clip(
            mask.sum(axis=1),
            a_min=1e-9,
            a_max=None,
        )

        return summed / counts


    @staticmethod
    def _l2_normalize(
        embeddings: NDArray[np.float32],
    ) -> NDArray[np.float32]:
        """
        L2-normalize embeddings.
        """

        norms = np.linalg.norm(
            embeddings,
            axis=1,
            keepdims=True,
        )

        norms = np.clip(
            norms,
            a_min=1e-12,
            a_max=None,
        )

        return embeddings / norms


    def _apply_mode_prefix(
            self,
            texts: tuple[str, ...],
            mode: Literal["query", "document"],
        ) -> tuple[str, ...]:
            """
            Apply model-specific text prefixes.

            E5 models require query/passage prefixes for optimal retrieval quality.
            """

            prefix = self._E5_PREFIXES.get(mode)

            if prefix is None:
                raise EmbeddingError(
                    f"Unsupported embedding mode: {mode}"
                )

            return tuple(
                prefix + text
                for text in texts
            )


    def _compute_embeddings(
        self,
        texts: tuple[str, ...],
    ) -> NDArray[np.float32]:

        inputs = self._tokenize(texts)

        hidden_states = self._run_inference(inputs)

        embeddings = self._mean_pool(
            hidden_states,
            inputs["attention_mask"],
    )
        return self._l2_normalize(embeddings)


    async def embed(
        self,
        texts: tuple[str, ...],
        *,
        mode: Literal["query", "document"],
    ) -> Embeddings:
        if not texts:
            return tuple()

        texts = self._apply_mode_prefix(
            texts,
            mode,
        )

        embeddings = await asyncio.to_thread(
            self._compute_embeddings,
            texts,
        )

        return tuple(
            tuple(map(float, embedding))
            for embedding in embeddings
        )

